# -*- coding: utf-8 -*-
"""Concurso - 25 de Junio de 2020: 🌙  NYX 🌙 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ae38YrEkoslqUaUqtG-poYZpsxJLflcU

<center><h1>  💍 🔮 @Milkajoyas_chile</h1></center>


<center>
  <p>🏠 Merced 738</p> 
  <p>💎 Local 202.</p>
  <p>☎️ +56 9 6177 2223</p>
  
  <h1>👸🏾👸🏼👸🏻👸</h1>
</center>
<center><p> 💎 Made with Swarovski Elements 💎 </center>

# Debes Pegar este codigo en tu ventana de instagram.

Recuerda cargar todos tus seguidores en la página!

<h1>Código Instagram</h1>

```
stats = document.querySelectorAll('ul[class="Mr508"]');
acum = [];
for(i of stats){
	elemento = i.innerText.replace(',','').replace(';','').split('\n');
    acum.push(elemento)
}
let csvContent = "data:text/csv;charset=utf-8," + acum.map(e => e.join(";")).join("\n");
var encodedUri = encodeURI(csvContent);
var link = document.createElement("a");
link.setAttribute("href", encodedUri);
link.setAttribute("download", "Mi_Concurso.csv");
document.body.appendChild(link); 
link.click()
```

# Debes darle Play ▶️
"""

def MiConcurso():
  import os
  import re
  import pandas as pd
  pd.set_option('display.max_rows', None)

  def concurso():
    acum = []
    for i in lista:
      participa   = i[0]
      eti         = [j for j in i[1].split() if len(j)>0]
      etiquetados = [re.findall(r'@.+',j) for j in eti]
      datos       = [[participa,[k for k in etiquetados if len(k)>0]]]
      acum = acum + datos
    df = pd.DataFrame(acum,columns=['Participante','Etiquetados'])
    df['formula'] = """=SUSTITUIR(SUSTITUIR(SUSTITUIR(C2;"[";"");"]";"");"'";"")"""
    return df

  archivos      = [i for i in os.listdir() if i.endswith('.csv')]
  lista         = pd.read_csv(archivos[0],header=None)[0]
  lista         = [i.split(';') for i in lista]

  concurso().to_excel('Descargame.xlsx')
MiConcurso()